/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/RyanFurrh/primaevus/public/models/flux-specimen-1/flux-specimen-1.gltf -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Mball029: THREE.Mesh
    Cube003: THREE.Mesh
    Cylinder001: THREE.Mesh
    Sphere: THREE.Mesh
  }
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial
    ['Default OBJ.001']: THREE.MeshPhysicalMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/flux-specimen-1.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.012']} position={[0.294, 0.56, -0.085]} rotation={[0, Math.PI / 2, 0]} scale={[1.005, 0.028, 1.005]} />
      <mesh geometry={nodes.Mball029.geometry} material={materials['Default OBJ.001']} position={[-0.085, 1.798, -0.294]} rotation={[-0.923, 0.643, 2.397]} scale={[0.465, 0.402, 0.641]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.005']} position={[0.294, 0.068, -0.085]} rotation={[0, Math.PI / 2, 0]} scale={[1.118, 0.031, 1.118]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.013']} position={[0.294, 0.471, -0.085]} rotation={[0, Math.PI / 2, 0]} scale={[0.783, 0.55, 0.783]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.006']} position={[0.294, 0.509, -0.085]} rotation={[0, Math.PI / 2, 0]} scale={0.35} />
    </group>
  )
}

useGLTF.preload('/flux-specimen-1.gltf')
