/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/computer1/computer1.gltf --transform --types
Files: public/models/computer1/computer1.gltf [862.23KB] > /Users/RyanFurrh/primaevus/app/components/computer1-transformed.glb [24.72KB] (97%)
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { PerspectiveCamera, useGLTF } from "@react-three/drei"
import { GLTF, GLTFLoader } from "three-stdlib"
import { useLoader } from "@react-three/fiber"

type GLTFResult = GLTF & {
  nodes: {
    Object_15: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    ["Material.006"]: THREE.MeshPhysicalMaterial
    ["Material.007"]: THREE.MeshStandardMaterial
    ["Material.009"]: THREE.MeshStandardMaterial
    ["Material.008"]: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>>

export default function Computer1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/models/computer1/computer1-transformed.glb"
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials["Material.006"]}
        position={[-0.265, 0.742, -0.834]}
        scale={[0.674, 0.77, 0.77]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.007"]}
        position={[0.873, 0.06, 0.509]}
        rotation={[0, -0.123, 0]}
        scale={[0.134, 0.019, 0.224]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials["Material.009"]}
        position={[0.873, 0.06, 0.509]}
        rotation={[0, -0.123, 0]}
        scale={[0.134, 0.019, 0.224]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials["Material.008"]}
        position={[0.933, 0.054, 0.509]}
        rotation={[0, 0.039, 0]}
        scale={[0.121, 0.017, 0.202]}
      />
    </group>
  )
}

useGLTF.preload("/models/computer1/computer1-transformed.glb")
