/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/RyanFurrh/primaevus/public/models/flux-specimen-1/flux-specimen-1.glb -t
*/

import * as THREE from "three"
import React from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF, GLTFLoader } from "three-stdlib"
import { useLoader } from "@react-three/fiber"

type GLTFAction = {
  name: string
  startTime: number
  duration: number
  tracks: any[]
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Mball029: THREE.Mesh
    Cube003: THREE.Mesh
    Cylinder001: THREE.Mesh
    Sphere: THREE.Mesh
  }
  materials: {
    ["Material.012"]: THREE.MeshStandardMaterial
    ["Basic Glass"]: THREE.MeshStandardMaterial
    ["Material.005"]: THREE.MeshStandardMaterial
    ["Material.013"]: THREE.MeshStandardMaterial
    ["Material.006"]: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function FluxSpecimen1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/models/flux-specimen-1/flux-specimen-1.glb"
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.012"]}
        position={[0, 0.56, 0]}
        scale={[1.005, 0.028, 1.005]}
      />
      <mesh
        geometry={nodes.Mball029.geometry}
        material={materials["Basic Glass"]}
        position={[0.209, 1.798, -0.379]}
        rotation={[-0.816, -0.504, 1.252]}
        scale={[0.465, 0.402, 0.641]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.005"]}
        position={[0, 0.068, 0]}
        scale={[1.118, 0.031, 1.118]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.013"]}
        position={[0, 0.471, 0]}
        scale={[0.783, 0.55, 0.783]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.006"]}
        position={[0, 0.509, 0]}
        scale={0.35}
      />
    </group>
  )
}

useGLTF.preload("/models/flux-specimen-1/flux-specimen-1.glb")
