// app/artifacts/components/models/Visor.tsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/visor/visor.gltf --types
*/

import * as THREE from "three"
import React from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFAction = {
  name: string
  startTime: number
  duration: number
  tracks: any[]
}

type GLTFResult = GLTF & {
  nodes: {
    bust: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Mball001: THREE.Mesh
    Cube002: THREE.Mesh
  }
  materials: {
    ["Default OBJ.001"]: THREE.MeshPhysicalMaterial
    ["Material.007"]: THREE.MeshStandardMaterial
    ["Material.008"]: THREE.MeshStandardMaterial
    ["Material.011"]: THREE.MeshPhysicalMaterial
    ["Material.009"]: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Visor(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/visor/visor.glb") as GLTFResult // Corrected path

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.bust.geometry}
        material={materials["Default OBJ.001"]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.278}
      />
      <group rotation={[0, Math.PI / 2, 0]} scale={[0.73, 0.201, 1]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials["Material.007"]} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials["Material.008"]} />
      </group>
      <mesh
        geometry={nodes.Mball001.geometry}
        material={materials["Material.011"]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.654}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.009"]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.73, 0.088, 0.73]}
      />
    </group>
  )
}

useGLTF.preload("/models/visor/visor.glb") // Corrected path
