import "../styles/globals.css"
import { Analytics } from "@vercel/analytics/react"
import { ArtifactProvider } from "./artifacts/components/ArtifactContext"
import { ThemeProvider } from "../components/theme-provider"
import { Sidebar } from "@/components/layout/Sidebar"
import { fontVars } from "@/app/fonts"

export const metadata = {
  title: "primae",
  description: "Generated by Next.js",
  icons: {
    icon: ["/favicon.ico"],
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${fontVars} pixelated font-mono`}
    >
      <ArtifactProvider>
        <body
          className="flex w-full h-screen bg-background text-foreground"
          style={{ WebkitFontSmoothing: "none" }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            value={{ light: "light", dark: "dark" }}
          >
            <Sidebar />

            {/* The rail is fixed-position (out of flow), so this fills the
                whole viewport and every surface centres in it. The gutter is
                the collapsed rail width on BOTH sides — symmetric, so content
                is centred in the viewport rather than pushed right by the
                rail. Surfaces that want the full width (Artifacts' 3D stage)
                opt out in their own layout. */}
            <div className="flex flex-col flex-1 h-full overflow-hidden">
              <main className="flex-1 overflow-y-auto overflow-x-hidden px-6 md:px-[110px]">
                {children}
                <Analytics />
              </main>
            </div>
          </ThemeProvider>
        </body>
      </ArtifactProvider>
    </html>
  )
}
