import "../styles/globals.css"
import { Analytics } from "@vercel/analytics/react"
import { ArtifactProvider } from "./artifacts/components/ArtifactContext"
import { ThemeProvider } from "../components/theme-provider"
import { Sidebar } from "@/components/layout/Sidebar"
import { SidebarProvider } from "@/components/layout/SidebarContext"
import { fontVars } from "@/app/fonts"

export const metadata = {
  title: "Primeūs",
  description: "Generated by Next.js",
  icons: {
    icon: ["/favicon.ico"],
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${fontVars} pixelated font-mono`}
    >
      <ArtifactProvider>
        <body
          className="flex w-full h-screen bg-background text-foreground"
          style={{ WebkitFontSmoothing: "none" }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            value={{ light: "light", dark: "dark" }}
          >
            {/* Wraps both the rail and the page area so a surface can reach
                the rail's collapsed state (the archive collapses it when a
                record opens onto the light table). */}
            <SidebarProvider>
              <Sidebar />

              {/* The rail is fixed-position (out of flow), so this fills the
                  whole viewport and every surface centres in it. The gutter is
                  the collapsed rail width on BOTH sides — symmetric, so content
                  is centred in the viewport rather than pushed right by the
                  rail. Keep this in step with Sidebar's collapsed width (w-18 = 72px).
                  Surfaces that want the full width (Artifacts' 3D stage) opt
                  out in their own layout. */}
              <div className="flex flex-col flex-1 h-full overflow-hidden">
                {/* Mobile-only advisory. In flow (not fixed) so it pushes the
                    surface down rather than sitting on top of it, and
                    relative z-40 so it clears the fixed rail at z-30 instead
                    of disappearing behind it. Below md the rail overlaps the
                    page anyway — that's the caveat this note is about. */}
                <div className="relative z-40 flex-shrink-0 border-b border-sand-300 bg-sand-100 px-6 py-2 text-center md:hidden dark:border-ink-100/40 dark:bg-ink-800">
                  <p className="m-0 font-mono text-[11px] leading-4 tracking-[0.04em] text-neptune-600 dark:text-neptune-400">
                    Work in progress — best viewed on desktop for now.
                  </p>
                </div>

                <main className="flex-1 overflow-y-auto overflow-x-hidden px-6 md:px-[72px]">
                  {children}
                  <Analytics />
                </main>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </ArtifactProvider>
    </html>
  )
}
